# Generated by Django 4.2 on 2023-06-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='penulis',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
