# Generated by Django 4.2 on 2023-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_remove_produk_status_alter_produk_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('penulis', models.CharField(default='Unknown', max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField(unique=True)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='product_pics')),
                ('label', models.CharField(choices=[('LBL1', 'Label 1'), ('LBL2', 'Label 2'), ('LBL3', 'Label 3'), ('LBL4', 'Label 4'), ('LBL5', 'Label 5'), ('LBL6', 'Label 6'), ('LBL7', 'Label 7'), ('LBL8', 'Label 8'), ('LBL9', 'Label 9'), ('LBL10', 'Label 10'), ('LBL11', 'Label 11'), ('LBL12', 'Label 12'), ('LBL13', 'Label 13'), ('LBL14', 'Label 14'), ('LBL15', 'Label 15'), ('LBL16', 'Label 16'), ('LBL17', 'Label 17'), ('LBL18', 'Label 18'), ('LBL19', 'Label 19'), ('LBL20', 'Label 20')], max_length=5)),
                ('kategori', models.CharField(choices=[('Self-Development', 'Self-Development'), ('Literacy Financial', 'Literacy Financial'), ('Technology', 'Technology'), ('College', 'College')], max_length=100)),
                ('jenis', models.CharField(choices=[('Buku', 'Buku'), ('Ebook', 'Ebook')], default='Ebook', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='produk',
            name='jenis',
            field=models.CharField(choices=[('Buku', 'Buku'), ('Ebook', 'Ebook')], default='Ebook', max_length=5),
        ),
    ]
