# Generated by Django 4.2 on 2023-06-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_ebook_alter_produk_jenis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produk',
            new_name='Buku',
        ),
    ]
