# Generated by Django 4.2 on 2023-06-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_rename_produk_buku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buku',
            options={'verbose_name_plural': 'Buku'},
        ),
        migrations.AlterModelOptions(
            name='ebook',
            options={'verbose_name_plural': 'Ebook'},
        ),
    ]
