# Generated by Django 4.2 on 2023-06-01 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produk', '0008_alter_buku_slug_alter_ebook_label_alter_ebook_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='produk',
        ),
        migrations.CreateModel(
            name='OrderProdukItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('buku_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produk.buku')),
                ('ebook_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produk.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='produk',
            field=models.ManyToManyField(to='produk.orderprodukitem'),
        ),
    ]
