# Generated by Django 4.2 on 2023-06-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='jenis',
            field=models.CharField(choices=[('Buku', 'Buku'), ('E-book', 'E-book')], max_length=8),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.CharField(choices=[('Self-Development', 'Self-Development'), ('Literacy Financial', 'Literacy Financial'), ('Technology', 'Technology'), ('College', 'College')], max_length=100),
        ),
    ]
