# Generated by Django 4.2 on 2023-06-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_alter_produk_jenis_alter_produk_kategori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produk',
        ),
    ]
